### ISSUE TITLE
IzzyOnDroid app inclusion

### ISSUE THREAD

**Issue by IzzySoft** [pewaru-333/ShikiApp#1]
Someone requested the inclusion of your app with the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) (by mail to me), so I've just taken a look. May I make 2 suggestions for improvement here, so it fits better?

For one, the scanners here reported:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

which can easily be avoided with a little addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

The other thing would be a little update to your [English Fastlane description](https://github.com/pewaru-333/ShikiApp/blob/master/fastlane/metadata/android/en-US/full_description.txt). Just from this description it's not fully clear what the app is. May I suggest altering line 1 there to something like

> ShikiApp is an inofficial client for shikimori.one, which currently is under development.

(and the Russian one accordingly – my Russian isn't good enough to propose the phrasing there)?

That said: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for e.g. your Readme and link it to [this place](https://apt.izzysoft.de/packages/org.application.shikiapp), where your app will show up at around 6 pm UTC with the next sync:

![image](https://github.com/user-attachments/assets/9a315c1f-3b73-466b-99c1-a555145a6426)

**Comment by pewaru-333** [comment]
Thank you! It was me who mailed you 😃.
I have added this code and changed .apk file in last release.
```
dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
```

Also I changed `full_description.txt` to be more informative.

Thank you very much again!

**Comment by IzzySoft** [comment]
Now, that was fast – thanks!

**Comment by IzzySoft** [comment]
Just a small follow-up question. The scanner here reported an unknown signature in the app, going by `org.application.*` with the wildcard part covering `adapter`, `selection` and `type`. As the prefix (`org.application`) is the same as the one of your app, I've looked inside the repo here but could not find a match – not even an `import`. Could you tell me where they come from? And out of curiosity maybe also what generates `/_generated/_ramcosta/_composedestinations/_moduleregistry`? Thanks in advance!

**Comment by pewaru-333** [comment]
I think files are under `build` folder, which is not included in repository. These files are generated by this library: `https://github.com/raamcosta/compose-destinations`.

**Comment by IzzySoft** [comment]
> I think files are under build folder, which is not included in repository.

Could you include them please? Else I'd need to also add `NonFreeComp` – as if it's not available openly, it's not foss but a NonFreeComponent.

> These files are generated by this library

Ah, thanks! Annotations. I was wondering what those `/_generated/*` stuff was I saw in smali of some apps.

**Comment by pewaru-333** [comment]
> Could you include them please?

This /build folder is generated at the runtime. Should I include it here? 
For example this is generated file under `/generated`:
```
package com.ramcosta.composedestinations.generated

import com.ramcosta.composedestinations.annotation.RootGraph
import com.ramcosta.composedestinations.generated.destinations.*
import com.ramcosta.composedestinations.generated.navgraphs.*
import com.ramcosta.composedestinations.spec.*
import org.application.shikiapp.screens.AnimeRatesScreen
import org.application.shikiapp.screens.AnimeScreen
import org.application.shikiapp.screens.CalendarScreen
import org.application.shikiapp.screens.CatalogScreen
import org.application.shikiapp.screens.CharacterScreen
import org.application.shikiapp.screens.ClubScreen
import org.application.shikiapp.screens.NewsDetail
import org.application.shikiapp.screens.NewsScreen
import org.application.shikiapp.screens.PersonScreen
import org.application.shikiapp.screens.ProfileScreen
import org.application.shikiapp.screens.SettingsScreen
import org.application.shikiapp.screens.UserScreen

/**
 * Class generated if any Composable is annotated with `@Destination`.
 * It aggregates all [DestinationSpec]s in their [NavGraphSpec]s.
 *
 * -------------------------------------------------------
 * **Legend:**                                           
 * * 🗺️: Navigation graph                              
 * * 📍: Destination                                   
 * * 🏁: Marks 🗺️/📍as the start of the parent graph   
 * * 🧩: Means 🗺️/📍is generated on external module          
 * -------------------------------------------------------
 *
 * * 🗺️[RootGraph]
 * * ∙∙∙∙∙∙∙∙↳📍🏁[NewsScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[AnimeRatesScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[AnimeScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[CalendarScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[CatalogScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[CharacterScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[ClubScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[NewsDetail]
 * * ∙∙∙∙∙∙∙∙↳📍[PersonScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[ProfileScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[SettingsScreen]
 * * ∙∙∙∙∙∙∙∙↳📍[UserScreen]
 */
internal object NavGraphs {

    val root = RootNavGraph
}
```

**Comment by IzzySoft** [comment]
> This /build folder is generated at the runtime.

You mean "at build time", right? In that case: no need to include them with the repo indeed (see my mail for some background).

**Comment by IzzySoft** [comment]
PS: Please let me know when a new release "as described in the mail" becomes available :wink:

**Comment by IzzySoft** [comment]
Thanks! But not as you described in your mail :wink: 

> How I release app:
> 1. Clean /build folder
> 2. Create changelog
> 3. Commit all changes in repository
> 4. Build signed .apk
> 5. Create release​​​​​​​

You didn't do that – you at least switch steps 3 and 4. Your APK was built from [this commit](https://github.com/pewaru-333/ShikiApp/commit/dfe972af5909689d0aeb753de6ad8dcb0f867564), according to the included `META-INF/version-control-info.textproto` (plus probably some uncommitted changes). Then you made 11 more commits and tagged [the last one](https://github.com/pewaru-333/ShikiApp/commit/63aae36605cdbfca8929950def5a225af83f7f9a) of it, finally attaching the APK to that. Hence the attached APK does not correspond to the tag it is attached to. Could that be? Could you maybe provide an APK that was really built from the commit the release points to, next time? :wink:

**Comment by IzzySoft** [comment]
Hi @pewaru-333, just wanted to let you know that alpha-0.1.13, being built from exactly the commit its tag points to, succeeded as reproducible build :partying_face: Green shield will come up in a few minutes. Please keep building the release APK this way :star_struck:

And here comes your [welcome toot](https://floss.social/@IzzyOnDroid/113775809982952427):

![image](https://github.com/user-attachments/assets/ec3b1772-f23e-4622-ad75-fc028cb9e52e)

Congrats! :star_struck:

**Comment by pewaru-333** [comment]
@IzzySoft, great! :+1:
