### ISSUE TITLE
Входит в другой аккаунт

### ISSUE THREAD

**Issue by OFGING** [pewaru-333/ShikiApp#2]
Нажал Войти, и вошёл в аккаунт другого человека
![Screenshot_20240903_121047_ShikiApp](https://github.com/user-attachments/assets/8bf660b2-ac8e-4b18-ad3e-a942a7151f81)

**Comment by pewaru-333** [comment]
Здравствуйте. Я пока не могу ни подтвердить, ни опровергнуть это, всё-таки аутентификация происходит на стороне сервера. Напишите, пожалуйста, ссылку на ваш профиль на сайте, посмотрю, в чём дело. Попробуйте добавить любое аниме в список избранного, если это не ваш аккаунт, то ничего не произойдёт.

**Comment by OFGING** [comment]
Ссылка на профиль:
https://shikimori.one/OFGING
Аниме добавляется в избранное, если добавить в список или изменить отзыв ничего не происходит.

**Comment by OFGING** [comment]
Изменения происходят на моем аккаунте

**Comment by pewaru-333** [comment]
@OFGING, здравствуйте. Возможно, я нашёл, в чём заключается ошибка. Сразу напишу, что это чисто визуальный "баг", в другой аккаунт вы, конечно, не зашли, как и не зайдут в ваш. В ближайшее время попытыюсь исправить ошибку, следите за обновлениями. Спасибо за создание данной темы!

**Comment by pewaru-333** [comment]
@OFGING, здравствуйте. Сегодня было выпущено обновление, которое затрагивает данную ошибку. Пожалуйста, отпишитесь, исчезла ли она. Но перед обновлением очистите данные приложения, либо удалите и заново установите его.

**Comment by OFGING** [comment]
Да
